org: faridaquino
service: api-websocket

provider:
  name: aws
  runtime: python3.12
  timeout: 29
  region: us-east-1
  stage: dev
  
  iam:
    role: arn:aws:iam::885475026169:role/LabRole
  
  httpApi:
    cors: true

  websocketsApiName: mi-api-websocket
  websocketsApiRouteSelectionExpression: $request.body.action

  environment:
    PEDIDO_TABLE: ${self:custom.pedidoTable}
    CONNECTIONS_TABLE: ${self:custom.connectionsTable}
    ACCESS_TOKEN: AQUIMERCADOTOKEN
    # Esto inyectar√° la URL de la cola creada abajo en las variables de entorno
    SQS_QUEUE_URL: { Ref: YAPAGADOSQueue }

custom:
  pedidoTable: Pedidos
  connectionsTable: Connections

functions:
  publishPedido:
    handler: handler.publishPedido
    events:
      - websocket:
          route: PublishPedido

  connectionHandler:
    handler: handler.connection_manager 
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect

  defaultHandler:
    handler: handler.default_handler
    events:
      - websocket: $default

  obtenerPedidoFiltro:
    handler: handler.pedidoFiltro
    events:
      - httpApi:
          path: /pedido
          method: get

  pagarPedido:
    handler: handler.pagarPedido
    events:
      - httpApi:
          path: /pagar
          method: post

  receiveWebhook:
    handler: handler.receiveWebhook
    events:
      - httpApi:
          path: /webhook
          method: post

resources:
  Resources:
    IncidentesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.pedidoTable}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.connectionsTable}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    YAPAGADOSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: YAPAGADOS.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        VisibilityTimeout: 60